<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <!-- تأكيد إصدار دوت نت 9 -->
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <!-- استخدام نسخة Swagger المتوافقة والمستقرة تماماً مع دوت نت 9 -->
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
  </ItemGroup>

</Project>